export const Employeeattendance = [
  {
    id: 1,
    name: "John Smith",
    department: "IT",
    date: "2024-01-15",
    checkIn: "09:15 AM",
    checkOut: "06:30 PM",
    status: "Present",
    workingHours: "8h 15m",
    overtime: "0h 15m",
  },
  {
    id: 2,
    name: "Lisa Wang",
    department: "Sales",
    date: "2024-01-15",
    checkIn: "08:45 AM",
    checkOut: "05:45 PM",
    status: "Present",
    workingHours: "8h 00m",
    overtime: "0h 00m",
  },
  {
    id: 3,
    name: "David Brown",
    department: "Sales",
    date: "2024-01-15",
    checkIn: "09:31 AM",
    checkOut: "06:00 PM",
    status: "Late",
    workingHours: "7h 30m",
    overtime: "0h 00m",
  },
  {
    id: 4,
    name: "Anna Lee",
    department: "Marketing",
    date: "2024-01-15",
    checkIn: "-",
    checkOut: "-",
    status: "Absent",
    workingHours: "0h 00m",
    overtime: "0h 00m",
  },
  {
    id: 5,
    name: "Mike Johnson",
    department: "Sales",
    date: "2024-01-15",
    checkIn: "09:00 AM",
    checkOut: "01:00 PM",
    status: "Half Day",
    workingHours: "4h 00m",
    overtime: "0h 00m",
  },
];
